name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change to your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to Cloudflare
        run: |
          # Add your deployment command here (e.g., using Cloudflare API or CLI)
          echo "Deploying to Cloudflare..."  # Placeholder for actual deployment
